apiVersion: v1
kind: Secret
metadata:
  name: catalog-db-credentials
  namespace: retail-app
type: Opaque
stringData:
  DB_ENDPOINT: "REPLACE_WITH_MYSQL_ENDPOINT"
  DB_PORT: "3306"
  DB_NAME: "catalog"
  DB_USER: "catalog_admin"
  DB_PASSWORD: "REPLACE_WITH_PASSWORD"
---
apiVersion: v1
kind: Secret
metadata:
  name: orders-db-credentials
  namespace: retail-app
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://REPLACE_WITH_POSTGRES_ENDPOINT:5432/orders"
  SPRING_DATASOURCE_USERNAME: "orders_admin"
  SPRING_DATASOURCE_PASSWORD: "REPLACE_WITH_PASSWORD"
