apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  namespace: retail-app
  labels:
    app: catalog
    app.kubernetes.io/component: catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
      - name: catalog
        image: public.ecr.aws/aws-containers/retail-store-sample-catalog:0.8.5
        ports:
        - containerPort: 8080
        env:
        - name: DB_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: catalog-db-credentials
              key: DB_ENDPOINT
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: catalog-db-credentials
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: catalog-db-credentials
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: catalog-db-credentials
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: catalog-db-credentials
              key: DB_PASSWORD
        - name: DB_MIGRATE
          value: "true"
        resources:
          requests:
            cpu: 128m
            memory: 256Mi
          limits:
            cpu: 256m
            memory: 512Mi
