apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
  namespace: retail-app
  labels:
    app: checkout
    app.kubernetes.io/component: checkout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
    spec:
      containers:
      - name: checkout
        image: public.ecr.aws/aws-containers/retail-store-sample-checkout:0.8.5
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_URL
          value: "redis://redis.retail-app.svc:6379"
        - name: ENDPOINTS_ORDERS
          value: "http://orders.retail-app.svc:8080"
        resources:
          requests:
            cpu: 128m
            memory: 256Mi
          limits:
            cpu: 256m
            memory: 512Mi
