apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: retail-app
  labels:
    app: orders
    app.kubernetes.io/component: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: public.ecr.aws/aws-containers/retail-store-sample-orders:0.8.5
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: orders-db-credentials
              key: SPRING_DATASOURCE_URL
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: orders-db-credentials
              key: SPRING_DATASOURCE_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: orders-db-credentials
              key: SPRING_DATASOURCE_PASSWORD
        - name: SPRING_PROFILES_ACTIVE
          value: "rabbitmq"
        - name: SPRING_RABBITMQ_HOST
          value: "rabbitmq.retail-app.svc"
        resources:
          requests:
            cpu: 128m
            memory: 256Mi
          limits:
            cpu: 256m
            memory: 512Mi
