apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: retail-app
  labels:
    app.kubernetes.io/name: cart
    app.kubernetes.io/component: cart
    app.kubernetes.io/part-of: retail-store
    Project: karatu-2025-capstone
spec:
  type: ClusterIP
  selector:
    app: cart
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
