apiVersion: v1
kind: Service
metadata:
  name: checkout
  namespace: retail-app
  labels:
    app.kubernetes.io/name: checkout
    app.kubernetes.io/component: checkout
    app.kubernetes.io/part-of: retail-store
    Project: karatu-2025-capstone
spec:
  type: ClusterIP
  selector:
    app: checkout
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
