apiVersion: v1
kind: Service
metadata:
  name: orders
  namespace: retail-app
  labels:
    app.kubernetes.io/name: orders
    app.kubernetes.io/component: orders
    app.kubernetes.io/part-of: retail-store
    Project: karatu-2025-capstone
spec:
  type: ClusterIP
  selector:
    app: orders
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
